org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
parchment_minecraft_version=1.20.1
parchment_mappings_version=2023.09.03

# Environment Properties
minecraft_version=1.20.1
minecraft_version_range=[1.20.1, 1.21)
forge_version=47.1.3
forge_version_range=[47.1.3,)
loader_version_range=[47,)

## Mod Properties

mod_id=mekagenjei
mod_name=MekaGenJei
mod_version=1.2
mod_group_id=com.devdyna.mekagenjei
mod_license=Ora Et Labora License
mod_authors=DevDyna
mod_description=Mekanism : Generator Addon to include some deep-use of some items

meka_version_range=[10.4.16,)
mekagen_version_range=[10.4.16,)

jei_version_range=[15.20.0.0,) 