org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.warning.mode=none

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)

forge_version=47.4.16
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=parchment
mapping_version=2023.09.03-1.20.1


mod_id=mekagenjei
mod_name=MekaGenJei
mod_version=1.2.1-20.1
mod_group_id=com.devdyna.mekagenjei
mod_license=Ora Et Labora License
mod_authors=DevDyna
mod_description=Mekanism : Generator Addon to include some deep-use of some items

meka_version=[10.4.16,)
mekagen_version=[10.4.16,)
jei_version=15.20.0.130
